name: Build Android Unity3D Application

on:
  push:
    branches:
      - main

env:
  UNITY_LICENSE_CONTENT: ${{ secrets.UNITY_LICENSE_CONTENT }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: docker/luisrojasnewmoon/unity:ubuntu-2022.2.3f1-android-1.0.1
      credentials:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_PWD }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Build
    - name: Build project
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: Android
    # Output
    - uses: actions/upload-artifact@v3
      with:
        name: Build
        path: build