name: Build Android Unity3D Application

on:
  push:
    branches:
      - main

env:
  UNITY_LICENSE_CONTENT: ${{ secrets.UNITY_LICENSE_CONTENT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up game-ci
      uses: r0adkll/game-ci@v0.11.0
      with:
        args: install-unity -f 2021.2.0f1

    - name: Build Android Unity3D application
      uses: r0adkll/game-ci@v0.11.0
      with:
        args: build android -f 2021.2.0f1

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: $UNITY_PROJECT_DIR/Builds/Android
        name: Android Build